version: '3'
services:
    web:
        image: nginx:alpine
        container_name: webserver-nginx
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "../isys/www:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8080:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            # - mysql
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: php-fpm-7.3
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../isys/www:/var/www/html"
    # composer:
    #     image: composer:latest
    #     container_name: composer-install
    #     volumes:
    #         - "../isys/www:/app"
    #     command: install
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: phpmyadmin
    #     ports:
    #         - "8080:80"
    #     environment:
    #         - PMA_ARBITRARY=1
    #         - PMA_HOST=${MYSQL_HOST}
    #     restart: always
    #     depends_on:
    #         - mysql
    # mysql:
    #     image: mysql:${MYSQL_VERSION}
    #     container_name: ${MYSQL_HOST}
    #     restart: always
    #     env_file:
    #         - ".env"
    #     environment:
    #         - MYSQL_DATABASE=${MYSQL_DATABASE}
    #         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #         - MYSQL_USER=${MYSQL_USER}
    #         - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - "./data/db/mysql:/var/lib/mysql"